# ML lab 08 Practice

---

# Tensor Manipulation

> YouTube Lecture: [link](https://www.youtube.com/watch?v=ZYX0FaqUeN4&feature=youtu.be)

## Tensor Manipulation

In [1]:
import tensorflow as tf
import numpy as np
import pprint as pp

### Simple ID array and slicing

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape)  # shape
print(t[0], t[1], t[-1])  # indexing
print(t[2:5], t[4:-1])  # slicing
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


### 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.,], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape)  # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


### Shape, Rank, Axis

- `[` 의 갯수가 rank 가 된다.

- rank 의 갯수가 n 일 경우, shape 도 n 개의 요소를 가진다.

- 가장 바깥쪽 `[` 은 axis 가 0, 안쪽으로 들어갈수록 1씩 증가한다.
  - axis 가 -1 이면 가장 안쪽 `[` 이다.

In [6]:
sess = tf.Session()

In [7]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

In [9]:
t = tf.constant([[1, 2],
                 [3, 4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [13]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

```python
[  # axis = 0, element 1개
    [  # axis = 1, element 2개
        [  # axis = 2, element 3개
            [1, 2, 3, 4],  # axis = 3, element 4개
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],
        
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]
    ]
]
```

### Matmul VS multiply

In [14]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session=sess)

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [16]:
(matrix1 * matrix2).eval(session=sess)  # 행렬곱이 아니다.

array([[1., 2.],
       [6., 8.]], dtype=float32)

### Broadcasting (<font color="red"><b>WARNING</b></font>)

shape 가 달라도 같은 것처럼 크기를 맞춰준다.

#### Operations between the same shapes

In [19]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval(session=sess)

array([[5., 5.]], dtype=float32)

#### Operations between the different shapes

In [21]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.]])
(matrix1 + matrix2).eval(session=sess)

array([[4., 5.]], dtype=float32)

In [22]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval(session=sess)

array([[4., 6.]], dtype=float32)

In [23]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval(session=sess)

array([[4., 5.],
       [5., 6.]], dtype=float32)

### Reduce mean

In [25]:
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [34]:
x = [  # axis = 0
    [1., 2.],  # axis = 1
    [3., 4.]
]
tf.reduce_mean(x).eval(session=sess)

# axis 를 지정안할시 ,모든 요소의 평균을 반환한다.

2.5

In [31]:
tf.reduce_mean(x, axis=0).eval(session=sess)
# (1, 3) (2, 4) 의 평균을 구하게 된다.

array([2., 3.], dtype=float32)

In [32]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [33]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

### Reduce sum

In [35]:
x = [
    [1., 2.],
    [3., 4.]
    ]

In [37]:
tf.reduce_sum(x).eval(session=sess)

10.0

In [38]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [39]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)

In [41]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=sess)
# Why use it?

5.0

### Argmax

최대값의 위치(Index)를 반환한다.

In [42]:
x = [
    [0, 1, 2],
    [2, 1, 0]
    ]

In [43]:
tf.argmax(x, axis=0).eval(session=sess)

array([1, 0, 0])

In [44]:
tf.argmax(x, axis=1).eval(session=sess)

array([2, 0])

In [45]:
tf.argmax(x, axis=-1).eval(session=sess)

array([2, 0])

### Reshape

보통 shape 의 마지막 값은 건드리지 않는다.

In [49]:
t = np.array(
    [
        [
            [0, 1, 2],
            [3, 4, 5]
        ],
              
        [
            [6, 7, 8],
            [9, 10, 11]
        ]
    ]
)

t.shape

(2, 2, 3)

In [51]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### Reshape (squeeze, expand)

In [54]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [55]:
tf.expand_dims([0, 1, 2], 1).eval(session=sess)

array([[0],
       [1],
       [2]], dtype=int32)

### One hot

자동적으로 rank 가 1 증가하게 된다.

In [56]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [57]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### Casting

In [59]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

In [60]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session=sess)

array([1, 0, 1, 0], dtype=int32)

### Stack

In [61]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim
tf.stack([x, y, z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [62]:
tf.stack([x, y, z], axis=1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### Ones and Zeros like

In [63]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [64]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

### Zip

In [65]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [66]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
