# ML lab 07-1 Practice

---

# Learning rate, Evaluation

> YouTube Lecture: [link](https://www.youtube.com/watch?v=oSJfejG2C3w&feature=youtu.be)

In [3]:
import tensorflow as tf

print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 1.13.1


## Training and Test datasets

In [4]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [17]:
X = tf.placeholder('float', [None, 3])
Y = tf.placeholder('float', [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(200+1):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        if step % 20 == 0:
            print('Step: {:<3} | Cost: {:<}\nW: {:<}\n'.format(step, str(cost_val), str(W_val)))
        
    # predict
    print('Prediction:', sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print('Accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

Step: 0   | Cost: 4.145891
W: [[-0.73032856 -0.23811142  1.4061222 ]
 [-1.4419069  -0.35315716  1.3425679 ]
 [ 0.8673327   1.3459196  -0.963588  ]]

Step: 20  | Cost: 1.0814314
W: [[-0.836629   -0.24798009  1.5222914 ]
 [-0.704783   -0.5682846   0.8205716 ]
 [ 1.1358007   1.1133536  -0.9994899 ]]

Step: 40  | Cost: 0.9473045
W: [[-1.0130224  -0.2342304   1.6849352 ]
 [-0.50804836 -0.54844564  0.6039979 ]
 [ 0.9896423   1.0646244  -0.8046019 ]]

Step: 60  | Cost: 0.847206
W: [[-1.1671396  -0.23121801  1.83604   ]
 [-0.37135696 -0.48900592  0.40786684]
 [ 0.8958503   0.98787355 -0.6340585 ]]

Step: 80  | Cost: 0.77119195
W: [[-1.3052919  -0.23161045  1.9745846 ]
 [-0.27005097 -0.41964412  0.23719913]
 [ 0.8352327   0.9092097  -0.49477693]]

Step: 100 | Cost: 0.71550596
W: [[-1.4308571  -0.23156817  2.1001074 ]
 [-0.19317292 -0.35578096  0.096458  ]
 [ 0.7987278   0.84139115 -0.3904535 ]]

Step: 120 | Cost: 0.6759187
W: [[-1.545936   -0.22939867  2.213017  ]
 [-0.13535656 -0.30426708 -0.0

## Big learning rate

`learning_rate = 1.5`

In [18]:
# 나머지 코드는 동일
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

Step: 0   | Cost: 3.637362
W: [[-0.36310768 -0.23795742  0.04847407]
 [-0.22905315  1.9454874  -1.7949975 ]
 [-1.1508183   1.4967723  -3.206234  ]]

Step: 20  | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 40  | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 60  | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 80  | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 100 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 120 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 140 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 160 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 180 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Step: 200 | Cost: nan
W: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

Prediction: [0 0 0]
Accuracy:  0.0


## Small learning rate

`learning_rate = 1e-10`

In [19]:
# 나머지 코드는 동일
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

Step: 0   | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133604]]

Step: 20  | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133604]]

Step: 40  | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133604]]

Step: 60  | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133604]]

Step: 80  | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133603]]

Step: 100 | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.2846576   0.29706597 -0.00133603]]

Step: 120 | Cost: 3.21221
W: [[-0.5883656   0.16126089 -1.2587235 ]
 [-1.2615099   0.8227709   0.11493136]
 [ 1.

## Non-normalized inputs

```python
xy = MinMaxScaler(xy)
```

최대값을 1, 최소값을 0 을 기준으로 값을 변경하여 Normalize