# ML lab 05 Practice

> YouTube Lecture: [link](https://www.youtube.com/watch?v=2FeWGgnyLSw&feature=youtu.be)

In [4]:
import tensorflow as tf

print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 1.13.1


In [1]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [8]:
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
# Hypothesis using sigmoid: tf.div(1, 1. + tf.exp(tf.matmil(X, W) + b))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [12]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [13]:
# Accuracy computation
# True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [41]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print(f'Step: {step:<6} | Cost: {cost_val}')
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
    print('\n<Hypothesis>\n', h[::100], '\n<Correct (Y)>\n', c[::100], '\n<Accuracy>\n', a)

Step: 0      | Cost: 0.9134717583656311
Step: 500    | Cost: 0.616692841053009
Step: 1000   | Cost: 0.5903218984603882
Step: 1500   | Cost: 0.5710660219192505
Step: 2000   | Cost: 0.5553658604621887
Step: 2500   | Cost: 0.5425057411193848
Step: 3000   | Cost: 0.5319332480430603
Step: 3500   | Cost: 0.5232032537460327
Step: 4000   | Cost: 0.5159605741500854
Step: 4500   | Cost: 0.5099214315414429
Step: 5000   | Cost: 0.5048603415489197
Step: 5500   | Cost: 0.5005976557731628
Step: 6000   | Cost: 0.49698981642723083
Step: 6500   | Cost: 0.4939216077327728
Step: 7000   | Cost: 0.4913003444671631
Step: 7500   | Cost: 0.48905110359191895
Step: 8000   | Cost: 0.48711296916007996
Step: 8500   | Cost: 0.48543620109558105
Step: 9000   | Cost: 0.48398011922836304
Step: 9500   | Cost: 0.48271095752716064
Step: 10000  | Cost: 0.48160097002983093

<Hypothesis>
 [[0.40252194]
 [0.65548855]
 [0.6932188 ]
 [0.77591133]
 [0.7133807 ]
 [0.77227855]
 [0.34666628]
 [0.8310102 ]] 
<Correct (Y)>
 [[0.]
 [1.

## Classifying diabetes

In [40]:
import tensorflow as tf
import numpy as np


xy = np.loadtxt('./data_files/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1, 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step % 500 == 0:
            print(f'Step: {step:<6} | Cost: {sess.run(cost, feed_dict=feed)}')
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print('\n<Hypothesis>\n', h[::100], '\n<Correct (Y)>\n', c[::100], '\n<Accuracy>\n', a)

Step: 0      | Cost: 1.0046786069869995
Step: 500    | Cost: 0.7358861565589905
Step: 1000   | Cost: 0.6840769052505493
Step: 1500   | Cost: 0.6444344520568848
Step: 2000   | Cost: 0.6130597591400146
Step: 2500   | Cost: 0.5882338881492615
Step: 3000   | Cost: 0.568527102470398
Step: 3500   | Cost: 0.5527905821800232
Step: 4000   | Cost: 0.5401297211647034
Step: 4500   | Cost: 0.5298591256141663
Step: 5000   | Cost: 0.5214581489562988
Step: 5500   | Cost: 0.5145305395126343
Step: 6000   | Cost: 0.5087741613388062
Step: 6500   | Cost: 0.5039564371109009
Step: 7000   | Cost: 0.499897301197052
Step: 7500   | Cost: 0.4964562654495239
Step: 8000   | Cost: 0.4935223460197449
Step: 8500   | Cost: 0.49100741744041443
Step: 9000   | Cost: 0.4888412654399872
Step: 9500   | Cost: 0.4869670271873474
Step: 10000  | Cost: 0.48533833026885986

<Hypothesis>
 [[0.37004143]
 [0.65464014]
 [0.6283606 ]
 [0.8023529 ]
 [0.7184534 ]
 [0.7179924 ]
 [0.39172474]
 [0.842677  ]] 
<Correct (Y)>
 [[0.]
 [1.]
 [1.