# ML lab 04-1 Practice

---

# Multi-variable linear regression

> YouTube Lecture: [link](https://www.youtube.com/watch?v=fZUV3xjoZSM)

## Not using matrix

H(x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>) = x<sub>1</sub>w<sub>1</sub> + x<sub>2</sub>w<sub>2</sub> + x<sub>3</sub>w<sub>3</sub>

In [5]:
import tensorflow as tf


x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = (x1 * w1) + (x2 * w2) + (x3 * w3) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 200 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  201.23405 
Prediction:
 [131.15482 176.04962 163.66536 182.74481 134.99866]
200 Cost:  24.318645 
Prediction:
 [143.24467 189.8934  177.66507 197.92847 145.4382 ]
400 Cost:  22.241716 
Prediction:
 [143.59108 189.65794 177.77374 197.9874  145.14583]
600 Cost:  20.374317 
Prediction:
 [143.91959 189.43466 177.87689 198.04236 144.8694 ]
800 Cost:  18.69482 
Prediction:
 [144.23125 189.22299 177.97491 198.09373 144.60811]
1000 Cost:  17.18406 
Prediction:
 [144.5269  189.0223  178.06802 198.14166 144.36115]
1200 Cost:  15.824739 
Prediction:
 [144.80736 188.83197 178.15643 198.18625 144.12772]
1400 Cost:  14.601314 
Prediction:
 [145.07347 188.6515  178.24046 198.2278  143.90715]
1600 Cost:  13.4998455 
Prediction:
 [145.32596 188.48035 178.32028 198.26637 143.69873]
1800 Cost:  12.507821 
Prediction:
 [145.56557 188.31804 178.39618 198.30219 143.50183]
2000 Cost:  11.614143 
Prediction:
 [145.79292 188.1641  178.46829 198.33536 143.31583]


## Using Matrix

In [6]:
import tensorflow as tf


x_data = [[73., 80., 75], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])  # Instance (데이터) 갯수는 정해져있지않음, 변수는 3개
Y = tf.placeholder(tf.float32, shape=[None, 1])  # Instance (데이터) 결과(예측)값 갯수는 정해져있지않음, 각 Instance 의 결과값은 1개

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    
    if step % 400 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  858.0801 
Prediction:
 [[133.01852]
 [148.97935]
 [152.65704]
 [164.4063 ]
 [112.22051]]
400 Cost:  19.695517 
Prediction:
 [[157.91092]
 [180.26999]
 [182.77448]
 [197.28662]
 [136.35974]]
800 Cost:  15.897276 
Prediction:
 [[157.25864]
 [180.71698]
 [182.57434]
 [197.14357]
 [136.94492]]
1200 Cost:  12.839224 
Prediction:
 [[156.67326]
 [181.1181 ]
 [182.39478]
 [197.01535]
 [137.46991]]
1600 Cost:  10.377197 
Prediction:
 [[156.14798]
 [181.47804]
 [182.23357]
 [196.9004 ]
 [137.94087]]
2000 Cost:  8.395036 
Prediction:
 [[155.67657]
 [181.80104]
 [182.08891]
 [196.79744]
 [138.36336]]
