# ML lab 04-2 Practice

---

# Loading Data from File

> YouTube Lecture: [link](https://www.youtube.com/watch?v=o2q4QNnoShY)

## Indexing, Slciing, Iterating of `numpy.array`

In [16]:
import numpy as np

### Example (1)

In [17]:
arr = [1, 2, 3, 4, 5]
a = np.array(arr)

In [18]:
a[1:3]

array([2, 3])

In [19]:
a[-1]

5

### a[0], a[1] 한꺼번에 변환

Python 의 기본 list 에서는 불가능

In [20]:
a[0:2] = 9
a

array([9, 9, 3, 4, 5])

### Example (2)

In [66]:
arr2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
b = np.array(arr2)

In [67]:
b[:, 1]

array([ 2,  6, 10])

In [68]:
b[-1]

array([ 9, 10, 11, 12])

In [69]:
b[-1, :]

array([ 9, 10, 11, 12])

In [70]:
b[-1, ...]  # Colon instances (`:`) can be replaced with dots (`...`) 

array([ 9, 10, 11, 12])

In [71]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Slicing Index 에 `[]` 를 사용할 경우

In [81]:
print(b[:, [-1]])
print(b[:, [-1]].shape)

[[ 4]
 [ 8]
 [12]]
(3, 1)


In [80]:
print(b[:, -1])
print(b[:, -1].shape)

[ 4  8 12]
(3,)


## Loading data from file

In [30]:
import numpy as np


xy = np.loadtxt('./data_files/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [39]:
x_data

array([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.],
       [ 53.,  46.,  55.],
       [ 69.,  74.,  77.],
       [ 47.,  56.,  60.],
       [ 87.,  79.,  90.],
       [ 79.,  70.,  88.],
       [ 69.,  70.,  73.],
       [ 70.,  65.,  74.],
       [ 93.,  95.,  91.],
       [ 79.,  80.,  73.],
       [ 70.,  73.,  78.],
       [ 93.,  89.,  96.],
       [ 78.,  75.,  68.],
       [ 81.,  90.,  93.],
       [ 88.,  92.,  86.],
       [ 78.,  83.,  77.],
       [ 82.,  86.,  90.],
       [ 86.,  82.,  89.],
       [ 78.,  83.,  85.],
       [ 76.,  83.,  71.],
       [ 96.,  93.,  95.]], dtype=float32)

In [40]:
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)

## Practice

In [82]:
import tensorflow as tf
import numpy as np


tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('./data_files/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print('-' * 30)
print(y_data.shape, y_data, len(y_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
------------------------------
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


In [90]:
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data}
    )
    if step % 400 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  5274.4736 
Prediction:
 [[229.28372]
 [262.1575 ]
 [265.42902]
 [286.90607]
 [198.32886]
 [141.19006]
 [215.21245]
 [160.60373]
 [239.18307]
 [215.4727 ]
 [205.56784]
 [195.9032 ]
 [276.23428]
 [231.8028 ]
 [213.9474 ]
 [265.1912 ]
 [219.22342]
 [260.07413]
 [265.7603 ]
 [238.82393]
 [251.26436]
 [244.64792]
 [241.314  ]
 [235.9092 ]
 [274.8503 ]]
400 Cost:  50.807632 
Prediction:
 [[160.1079 ]
 [181.22504]
 [184.49753]
 [199.3546 ]
 [136.66797]
 [ 96.89708]
 [149.9327 ]
 [112.5013 ]
 [164.77832]
 [148.05544]
 [142.72818]
 [135.14319]
 [192.05707]
 [161.13373]
 [148.76294]
 [183.4208 ]
 [151.89134]
 [181.59169]
 [185.07532]
 [166.4977 ]
 [174.82127]
 [169.15567]
 [168.07625]
 [164.84029]
 [190.34895]]
800 Cost:  37.48229 
Prediction:
 [[158.97905 ]
 [181.72922 ]
 [183.99501 ]
 [199.2988  ]
 [137.10945 ]
 [ 98.19819 ]
 [150.09944 ]
 [112.861435]
 [166.28159 ]
 [150.70045 ]
 [142.93889 ]
 [136.36052 ]
 [191.06786 ]
 [159.73425 ]
 [149.26282 ]
 [184.22878 ]
 [150.53947 ]
 [181.67

In [91]:
# Ask my score
print('Your score will be ', sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print('Other score will be ', sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[170.83582]]
Other score will be  [[166.39517]
 [185.99599]]


데이터를 재학습시킬 경우  
출력되는 결과의 오차가 크다.

## Queue Runners (Full Code)

In [94]:
import tensorflow as tf


filename_queue = tf.train.string_input_producer(
    ['./data_files/data-01-test-score.csv'],
    shuffle=False,
    name='filename_queue'
)
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# Collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch, = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_batch, Y: y_batch})
    if step % 400 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  59680.43 
Prediction:
 [[393.75623]
 [467.99768]
 [463.74194]
 [505.6883 ]
 [355.1842 ]
 [262.42017]
 [381.09637]
 [286.22787]
 [437.0345 ]
 [405.8687 ]]
400 Cost:  10.172785 
Prediction:
 [[155.97052]
 [182.95004]
 [182.48428]
 [199.49686]
 [137.87628]
 [102.47931]
 [151.86852]
 [116.22436]
 [170.95663]
 [159.74663]]
800 Cost:  8.6322 
Prediction:
 [[155.61862]
 [183.20615]
 [182.37817]
 [199.48605]
 [138.15378]
 [102.92448]
 [151.82529]
 [116.12323]
 [171.48126]
 [160.52452]]
1200 Cost:  7.5281525 
Prediction:
 [[155.31937]
 [183.42754]
 [182.28998]
 [199.47491]
 [138.39682]
 [103.30218]
 [151.77985]
 [116.02054]
 [171.9265 ]
 [161.1763 ]]
1600 Cost:  6.734626 
Prediction:
 [[155.06451]
 [183.61926]
 [182.21669]
 [199.46371]
 [138.61003]
 [103.62303]
 [151.73341]
 [115.91829]
 [172.30481]
 [161.72261]]
2000 Cost:  6.162429 
Prediction:
 [[154.8472  ]
 [183.78554 ]
 [182.15579 ]
 [199.45264 ]
 [138.79733 ]
 [103.895935]
 [151.68698 ]
 [115.81799 ]
 [172.62668 ]
 [162.18079 ]]

### `shuffle_batch`

In [ ]:
"""
min_after_dequeue defines how big a buffer we will
  randomly sample from -- bigger means better
  shuffling but slower start up and more memory used.
capacity must be larger than min_after_dequeue and
  the amount larger determines the maximum we will prefetch.
  Recommendation: min_after_dequeue + (num_threads + a small safety margin) * batch_size
"""
min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch(
    [example, label],
    batch_size=batch_size,
    capacity=capacity,
    min_after_dequeue=min_after_dequeue
)