# ML lab 06-1 Practice

> YouTube Lecture: [link](https://www.youtube.com/watch?v=VRnubDzIy3A)

In [1]:
import tensorflow as tf

print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 1.13.1


## Softmax Classification

In [6]:
x_data = [
    [1, 2, 1, 1],
    [2, 1, 3, 2],
    [3, 1, 3, 4],
    [4, 1, 5, 5],
    [1, 7, 5, 5],
    [1, 2, 5, 6],
    [1, 6, 6, 6],
    [1, 7, 7, 7],
]
y_data = [
    [0, 0, 1],  # 2
    [0, 0, 1],  # 2
    [0, 0, 1],  # 2
    [0, 1, 0],  # 1
    [0, 1, 0],  # 1
    [0, 1, 0],  # 1
    [1, 0, 0],  # 0
    [1, 0, 0],  # 0
]

X = tf.placeholder('float', [None, 4])
Y = tf.placeholder('float', [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 400 == 0:
            print('Step: {:<6} | Cost: {}'.format(
                step,
                sess.run(cost, feed_dict={X: x_data, Y: y_data})
            ))
    
    print('-' * 30)
    print('Testing & One-hot encoding\n')
    # Testing & One-hot encoding
    all = sess.run(hypothesis, feed_dict={X:[
        [1, 11, 7, 9],
        [1, 3, 4, 3],
        [1, 1, 0, 1]
    ]})
    print('<ALL>\n{} \n\n tf.arg_max: {}'.format(
        all,
        sess.run(tf.arg_max(all, 1))
    ))

Step: 0      | Cost: 3.0893852710723877
Step: 400    | Cost: 0.5143839120864868
Step: 800    | Cost: 0.3619782328605652
Step: 1200   | Cost: 0.2369900941848755
Step: 1600   | Cost: 0.19677014648914337
Step: 2000   | Cost: 0.16778963804244995
------------------------------
Testing & One-hot encoding

<ALL>
[[3.1224260e-02 9.6876657e-01 9.1404727e-06]
 [6.8967032e-01 2.8804198e-01 2.2287654e-02]
 [2.1299636e-08 4.1028202e-04 9.9958974e-01]] 

 tf.arg_max: [1 0 2]
